AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a static domain s3 bucket
Parameters:
  WebUIOriginAccessIdentityId:
    Description: The ID of the OriginaAccessIdentity
    Type: String
Resources:
  LomodoroContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: 'lomodoro-ui-bucket'
      WebsiteConfiguration:
        ErrorDocument: '404.html'
        IndexDocument: index.html

  LomodoroContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LomodoroContentBucket
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS:
                - !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${WebUIOriginAccessIdentityId}
            Action:
              - 's3:GetObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'LomodoroContentBucket'
                  - '/*'

Outputs:
  LomodoroBucketName:
    Value: !Ref LomodoroContentBucket
    Description: The S3 bucket name
  WebsiteURL:
    Value: !Join ['', ['http://', !GetAtt [LomodoroContentBucket, DomainName]]]
    Description: Name of S3 bucket that hosts the lomodoro content
