AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create a custom domain name and certificate

Parameters:
  DomainName:
    Description: The top level domain (e.g. sync.nortxe.com)
    Type: String
  HostedZoneId:
    Description: ID of the hosted zone you are creating the certificate in. Alphanumeric string.
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  LomodoroDomainCertificate:
    Value: !Ref Certificate
    Description: Web UI Custom Domain Certificate
