AWSTemplateFormatVersion: 2010-09-09
Description: Route 53 routing to domain name
Parameters:
  DomainName:
    Description: Domain name such as www.mysite.com
    Type: String
  HostedZoneId:
    Description: ID of the Hosted Zone to create the cert increase
    Type: String
  CloudFrontDistroDomainName:
    Description: CD Distro ID
    Type: String
    Default: true

Resources:
  CFAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZoneId #Zone ID of the target domain in ROUTE53
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 #Always is this ID when targeting a CF Distro
        DNSName: !Ref CloudFrontDistroDomainName
