AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create a custom domain name and certificate

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      # naked domain
      DomainName: 'johniacoucci.com'
      # add www to certificate
      SubjectAlternativeNames:
        - 'www.johniacoucci.com'
      ValidationMethod: DNS
      DomainValidationOptions:
        # DNS record for the naked domain
        - DomainName: 'johniacoucci.com'
          HostedZoneId: 'Z02392231R5VC2Q6ST5ES'
        # DNS record for the www domain
        - DomainName: 'www.johniacoucci.com'
          HostedZoneId: 'Z02392231R5VC2Q6ST5ES'

Outputs:
  LomodoroDomainCertificate:
    Value: !Ref Certificate
    Description: Web UI Custom Domain Certificate
