AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create a custom domain name and certificate

Parameters:
  DomainName:
    Description: The top level domain
    Type: String
  HostedZoneId:
    Description: ID of the hosted zone you are creating the certificate in. Alphanumeric string.
    Type: String
  AutoCertApproval:
    Description: Turn on automatic approval of certificates through DNS when set to true. Default true.
    Type: String
    Default: 'true'

Conditions:
  IsAutoCert: !Equals
    - !Ref AutoCertApproval
    - true

Resources:
  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  LomodoroDomainCertificate:
    Condition: IsAutoCert
    Value: !Ref Certificate
    Description: Lomodoro web cert for ssl
